# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7f4830f118c09561d9bb7fd4f9e46d5593771ea606c052637524a1b3619587ca17086bd7c1df99739b5422877f36ed275d0602b34315acd0c331cb348ef890

test:
  secret_key_base: dd4786b9fd23c59d0a97630c2eba75e5a5e4cc8075b2236528a4b56ac92b51ed4db3a4c50f12687816be81792f7d5ebdb9ba6ea787f68f2b8933ea10e7412778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
